# Enable Vi mode
set -g mode-keys vi
set -g status-keys vi

# Start selection with 'v'
bind-key -T copy-mode-vi v send-keys -X begin-selection

# Copy to system clipboard (Logic for Mac vs Linux)
if-shell "uname | grep -q Darwin" \
    "bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'pbcopy'" \
    "bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -sel clip -i'"

# Paste buffer
bind-key p paste-buffer

# Essential Settings for both OS's
set -g mouse off
set -s escape-time 0
set -g history-limit 50000

# Resize panes with prefix + h/j/k/l
bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
